services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - temp_environments:/app/temp_environments
      - ./:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - TEMP_ENV_BASE_DIR=/app/temp_environments
    restart: unless-stopped
    networks:
      - app-network
    user: "1001:1001" # This matches the UID:GID of the nextjs user in the Dockerfile

volumes:
  temp_environments:
    driver: local

networks:
  app-network:
    driver: bridge
